name: CI Pipeline

on:
  push:
    branches: [ main ]   # runs when you push to main branch


jobs:
  build:
    runs-on: windows-latest   # GitHub gives you a Linux VM to run this

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build and test
        run: ./gradlew clean build --no-daemon
